import LocalizedStrings from "react-localization";

export const Localizations = new LocalizedStrings({
  en: {
    description: "An app that helps improve your\\mental math skills",
    home: "Home",
    features: "Features",
    gameModes: "3 different game modes",
    multiplayer: "Multiplayer to play against your friends",
    leaderboard: "Global leaderboard",
    customProfile: "Customizable profile",
    languages: "Support for 8 languages",
    darkMode: "Dark/light mode",
    github: "GitHub",
    email: "Email",
    website: "Website",
    privacyPolicy: "Privacy Policy",
    allRightsReserved: "All rights reserved.",
  },
  es: {
    description:
      "Una aplicación que ayuda a mejorar tus\\habilidades de cálculo mental",
    home: "Inicio",
    features: "Características",
    gameModes: "3 modos de juego diferentes",
    multiplayer: "Multijugador para jugar con amigos",
    leaderboard: "Clasificación global",
    customProfile: "Perfil personalizable",
    languages: "Soporte para 8 idiomas",
    darkMode: "Modo oscuro/claro",
    github: "GitHub",
    email: "Correo electrónico",
    website: "Sitio web",
    privacyPolicy: "Política de privacidad",
    allRightsReserved: "Todos los derechos reservados.",
  },
  zh: {
    description: "一个帮助提高你\\心算能力的应用程序",
    home: "首页",
    features: "功能",
    gameModes: "3 种不同的游戏模式",
    multiplayer: "多人游戏，与朋友对战",
    leaderboard: "全球排行榜",
    customProfile: "可自定义个人资料",
    languages: "支持 8 种语言",
    darkMode: "深色/浅色模式",
    github: "GitHub",
    email: "电子邮件",
    website: "网站",
    privacyPolicy: "隐私政策",
    allRightsReserved: "版权所有。",
  },
  fr: {
    description:
      "Une application qui aide à améliorer vos\\compétences en calcul mental",
    home: "Accueil",
    features: "Fonctionnalités",
    gameModes: "3 modes de jeu différents",
    multiplayer: "Multijoueur pour jouer avec des amis",
    leaderboard: "Classement mondial",
    customProfile: "Profil personnalisable",
    languages: "Support pour 8 langues",
    darkMode: "Mode sombre/clair",
    github: "GitHub",
    email: "E-mail",
    website: "Site web",
    privacyPolicy: "Politique de confidentialité",
    allRightsReserved: "Tous droits réservés.",
  },
});
